npx nest g module prisma
npx nest g service prisma
npx nest g module auth
npx nest g service auth
npx nest g controller auth
npx nest g module plan
npx nest g service plan
npx nest g controller plan
npx nest g module blocks
npx nest g service blocks
npx nest g controller blocks
npx nest g module checkins
npx nest g service checkins
npx nest g controller checkins
npx nest g module dashboard
npx nest g service dashboard
npx nest g controller dashboard
npx nest g module settings
npx nest g service settings
npx nest g controller settings
